############################################################################
### This is the tmux setup file
### Author: Yunfan
############################################################################
# set -g default-shell "/bin/zsh"
# set -g default-command "zsh -l"
# set -g default-terminal "tmux-256color"
# set -a terminal-overrides ",*256col*:RGB"

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-b
bind-key C-b send-prefix

# Show tmux positions in titles
# set -g set-titles on
set -g focus-events on
setw -g mode-keys vi
set -g mouse off
set -g status-position bottom

# -r means repeat
bind -r h select-pane -L
bind -r l select-pane -R
bind -r j select-pane -D
bind -r k select-pane -U

# Use Alt-hjkl to switch panes
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# Use Alt-arrow keys to switch panes
bind -n M-Left  select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up    select-pane -U
bind -n M-Down  select-pane -D

bind -r -T prefix M-Up    resize-pane -U 5
bind -r -T prefix M-Down  resize-pane -D 5
bind -r -T prefix M-Left  resize-pane -L 5
bind -r -T prefix M-Right resize-pane -R 5

bind -r -T prefix C-Up    resize-pane -U
bind -r -T prefix C-Down  resize-pane -D
bind -r -T prefix C-Left  resize-pane -L
bind -r -T prefix C-Right resize-pane -R

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

bind-key -n C-S-Left swap-window -t -1\; select-window -t -1
bind-key -n C-S-Right swap-window -t +1\; select-window -t +1

# bind-key -n C-S-Left swap-window -t -1
# bind-key -n C-S-Right swap-window -t +1

bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -i -f -selection primary | xclip -i -selection clipboard"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"

# Disable prompt when killing window and pane
bind & kill-window
bind x kill-pane

# set -g default-terminal "screen-256color"
set -s default-terminal 'tmux-256color'

# Easy config reload
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'dracula/tmux'

# it can accept `session`, `smiley`, `window`, or any character.
set -g @dracula-show-left-icon window
set -g @dracula-show-timezone false
set -g @dracula-show-fahrenheit false
set -g @dracula-show-location false
set -g @dracula-left-icon-padding 1
set -g @dracula-border-contrast true
set -g @dracula-military-time true

run -b '~/.tmux/plugins/tpm/tpm'